project:
    type: book

book:
    title: "Best Book"
    author: "V Sai Prabhav"
    date: "9/23/2024"
    chapters:
        - index.qmd
        - problem_1.qmd
        - problem_2.qmd
        - intro.qmd
        - summary.qmd
        - references.qmd

bibliography: references.bib

execute:
    freeze: auto

format:
    html:
        theme: superhero
    pdf:
        documentclass: scrreprt
