project:
  type: book

book:
  title: "Best Book"
  author: "V Sai Prabhav"
  date: "9/23/2024"
  chapters:
    - index.qmd
    - question-1.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



